#!/usr/bin/env bash

limelight -m config width 2
limelight -m config radius 12
limelight -m config placement exterior
limelight -m config active_color #FFE4E1
limelight -m config normal_color #FFE4E1

echo "limelight configuration loaded.."
