#!/usr/bin/env bash

limelight -m config width 1.5
limelight -m config radius 10
limelight -m config placement exterior
limelight -m config active_color 0xFFFA8072
limelight -m config normal_color 0x00FA8072

echo "limelight configuration loaded.."
