#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
# - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.97
yabai -m config normal_window_opacity        0.97
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xffd8bfd8
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd8bfd8
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  38
yabai -m config bottom_padding               3
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   05


# Renaming the spaces
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI

# float applications. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Messenger$" manage=off
yabai -m rule --add app="^Minecraft 1.19$" manage=off
yabai -m rule --add app="^Minecraft Launcher$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Python$" manage=off
yabai -m rule --add app="^CCleaner$" manage=off

# float system preferences
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^Archive Utility$' manage=off
yabai -m rule --add title='Settings$' manage=off

#Particular opacity
yabai -m rule --add app="Obsidian" opacity=1.0
yabai -m rule --add app="Kitty" opacity=1.0

# Some Settings For Simple-Bar
# Refresh spaces widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"


yabai -m signal --add event=space_destroyed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh spaces widget on display focus change
yabai -m signal --add event=display_changed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh spaces widget on window resize
yabai -m signal --add event=window_resized action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on space change
yabai -m signal --add event=space_changed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh spaces widget on when focused application changes
yabai -m signal --add event=window_focused action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e \
                            'tell application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh spaces widget on when focused application changes
yabai -m signal --add event=application_front_switched action="osascript -e \
                            'tell application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-process-jsx\"'"

# Refresh spaces widget on when an application window is closed
yabai -m signal --add event=window_destroyed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-spaces-jsx\"'"

# Refresh process widget when current window title changes
yabai -m signal --add event=window_title_changed action="osascript -e 'tell \
                            application id \"tracesOf.Uebersicht\" \
                            to refresh widget id \"simple-bar-process-jsx\"'"

echo "yabai configuration loaded.."
